import React, { useState, useEffect } from 'react';
import InteractiveTimetableGrid from '../../components/timetable/InteractiveTimetableGrid';

const TimetablePage = () => {
  const [timetableData, setTimetableData] = useState(null);

  useEffect(() => {
    // In a real application, we would fetch this specific teacher's timetable from Firebase.
    // For now, it is empty until generated by the Admin/HOD.
    setTimetableData(null);
  }, []);

  return (
    <div className="dashboard-container">
      <div className="dashboard-header" style={{ marginBottom: '20px' }}>
        <div>
          <h2>My Timetable</h2>
          <p>View your weekly lecture and practical schedule here.</p>
        </div>
      </div>

      <div className="glass-card" style={{ padding: '40px', textAlign: 'center' }}>
        {timetableData ? (
          <InteractiveTimetableGrid timetable={timetableData} onCellClick={() => {}} />
        ) : (
          <div>
            <h3 style={{ color: '#fff', marginBottom: '10px' }}>No Timetable Assigned</h3>
            <p style={{ color: 'rgba(255,255,255,0.7)' }}>Your timetable has not been generated by the HOD/Admin yet.</p>
          </div>
        )}
      </div>
    </div>
  );
};

export default TimetablePage;
